services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/prometheus/data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    network_mode: host
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./observability/loki/config.yml:/etc/loki/config.yml:ro
      - ./observability/loki/data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    network_mode: host
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./observability/promtail/config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log/traefik:ro

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./observability/grafana/data:/var/lib/grafana

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    network_mode: host
    command: ["--config=/etc/otel/config.yml"]
    volumes:
      - ./observability/otel/config.yml:/etc/otel/config.yml:ro
